### ISSUE TITLE
Economic features!

### ISSUE THREAD

**Issue by SebastianLasch** [DanielPollithy/TransliterationApplication#101]
Servus Dani,
das sind keine Bugs, aber nach längerem Arbeiten, sind 2 Punkte aufgetreten, welche den Workflow stark stören (sind nicht zwingend notwendig, wäre aber sehr hilfreich, wenn man das anpassen könnte...):
1. Wenn man auf 'Kommentar' klickt, wäre es super, wenn der cursor direkt ins Schreibfeld geht, ohne dass man nochmal extra darauf klicken muss...

2. Bei der Ansicht im Editor=>Index sollte  'Show **100** entries voreingestellt werden, bzw. immer automatisch die letzte Seite angezeigt werden. Wenn ich jetzt ein Bild hochlade (ich habe bereits mehr als 20 Bilder bearbeitet) muss ich entweder die Anzahl der gezeigten Einträge ändern (jedes mal) oder auf die letzte Seite gehen.. Vielleicht wäre es am logischsten, wenn man automatisch auf die letzte Seite kommt, nach dem Upload (bzw. auf die Seite, auf welcher das zuletzt hochgeladene Bild zu finden ist; darum geht es letztendlich, da es sonst nach ein paar hundert Bildern sehr unübersichtlich wird).

Wir könnten morgen telefonieren oder uns an der Uni treffen...

Beste Grüße

**Comment by DanielPollithy** [comment]
Hallo, Basti!
Zu Punkt 1 ist mir nicht ganz klar, was du meinst. Punkt 2 verstehe ich auf jeden Fall und ich würde das jetzt so lösen, dass die Tabelle standardmäßig von neu nach alt sortiert ist (davor war es ja andersherum). Ich könnte mir vorstellen, dass das schon reicht, um die Übersichtlichkeit wiederherzustellen.
Viele Grüße
Daniel

**Comment by SebastianLasch** [comment]
Servus Daniel!
Zu 1.: (ist nicht so wichtig) Wenn ich auf 'Kommentar' klicke, öffnet sich zwar das Feld, um Kommentare anzugeben, allerdings muss man nochmal in das Feld klicken, um schreiben zu können...

Zu 2.: Das ist super so!! Sehr viel besser, als mein Vorschlag..

Beste Grüße,
Basti
