### ISSUE TITLE
Uploaded Img and Fragments not visible..

### ISSUE THREAD

**Issue by SebastianLasch** [DanielPollithy/TransliterationApplication#107]
Hallo @DanielPollithy ,
es ist nun das erste Mal ein Problem aufgetaucht:
- Ich habe 9 Fotos bearbeitet
- Nach dem Neustart des Computers und dem neuen Einloggen in neo4j und GIAnT treten folgende Probleme auf:
1. Die 9 Fotos werden zwar mit eigener ID angezeigt, allerdings sieht man schon am Erstellungsdatum, dass etwas nicht stimmen kann (alle 1.1.1970)
2. Die Fragmente werden im Index mit 0/0 angezeigt
![image](https://user-images.githubusercontent.com/30180465/31813233-ed728aaa-b585-11e7-86fa-8621a5bac416.png)
3.  Innerhalb der Fotos sind Fragmente vorhanden, die Kommentare sind weg
![image](https://user-images.githubusercontent.com/30180465/31813284-0f9cfc3c-b586-11e7-9541-8676f439eef3.png)
4. Im Editor sind zwar die Token, usw. sichtbar, aber das Bild fehlt, obwohl sie im 'media' Ordner sind
![image](https://user-images.githubusercontent.com/30180465/31813318-38587a52-b586-11e7-9a39-8e2c635c253f.png)
![image](https://user-images.githubusercontent.com/30180465/31813345-4a67694c-b586-11e7-80fc-6a305c64ddbf.png)
5. In der DB werden zwar Token angezeigt, allerdings sind diese fast alle leer (kein 'value' oder sonstige Props)
![image](https://user-images.githubusercontent.com/30180465/31813416-875f5e22-b586-11e7-8d3c-3d8f82cb9589.png)

Ich habe keine Ahnung an was das liegen könnte, da ich bei der Vorgehensweise nichts geändert habe...
Ich werde jetzt versuchen den PC nochmal neu zu starten und hoffe es funktioniert dann...

**Comment by SebastianLasch** [comment]
Hier noch ein Nachtrag:
- Ich habe in die xml Dateien geschaut und dort sieht man die Token mit den Props
- Anscheinend liegt es am Tool selber, da ich auch nicht bei den Fragmenten von 'In Bearbeitung' auf 'Fertig' gehen kann
- Löschen kann ich die fehlerhaften Bilder auch nicht
- Neue Bilder kann ich hochladen, welche auch korrekt angezeigt werden

**Comment by DanielPollithy** [comment]
Note for future readers:
This was not a problem of the application. The neo4j database got corrupted due to the fact that a cloud synchronisation service was working meanwhile changes were made to the database.

Therefore the "restore from file system" function has been added.
