### ISSUE TITLE
creation of duplicate MetaGroups from within a single fragment

### ISSUE THREAD

**Issue by SebastianLasch** [DanielPollithy/TransliterationApplication#96]
![metaframes](https://user-images.githubusercontent.com/30180465/28218007-801a2b9a-68b7-11e7-9057-c959c5e8eec5.JPG)
![metaframes2](https://user-images.githubusercontent.com/30180465/28218008-801c0906-68b7-11e7-860b-b022aa2deeb5.JPG)
![metaframes3](https://user-images.githubusercontent.com/30180465/28218009-80407c78-68b7-11e7-9605-62bb4bf8d392.JPG)

**Comment by DanielPollithy** [comment]
Hi @bastino089 !
Ich habe gerade versucht den Fehler nachzubilden. Hierzu habe ich folgendes Scritte im Editor erstellt:
Mehrere Frames mit dem gleichen Namen in einem Scritte.

![3](https://user-images.githubusercontent.com/7472988/28332594-adbfdeb4-6bf5-11e7-91e2-6f9188432c36.png)

Wenn ich das zu Neo4j hinzufüge, dann kommt es jedoch nicht zu beschriebenem Problem:
![4](https://user-images.githubusercontent.com/7472988/28332624-c5adb85c-6bf5-11e7-8b79-856f8ac9f605.png)

Könntest du mir eine Konfiguration erklären, in der es zu dem Fehler kommt?

**Comment by SebastianLasch** [comment]
Ich schicke dir am besten das Beispiel, wo ich den Bug entdeckt habe. Und dann versuche ich nochmal an anderen Beispielen, ob das jedesmal passiert oder nur einmalig vorgekommen ist... 
Reicht dir das bis morgen?

**Comment by SebastianLasch** [comment]
Hey @DanielPollithy,
also der Fehler tritt weiterhin auf. Ich hab es jetzt nochmal an einem anderen Foto probiert. Und zwar wenn du folgendermaßen vorgehst:
1. Fragment für 1 (neues) Foto erstellen
2. Innerhalb des gleichen Fragment UND der GLEICHEN HAND zwei (oder mehr) Frames über Token legen. Diese Frames werden gleich benannt (bspw. 'Reference'), da sie später auch zur gleichen MetaGroup gehören sollen. D.h. der value der beiden Frames = 'Reference', ABER die Frames selber haben jeweils weitere Props, welche abweichen (bei mir bspw. 'subcat1' und 'subcat2').
3. Übertragen in neo4j

=> Es werden 2 gleichnamige Metagroups erstellt, obwohl es nur einer (='Reference') sein sollte und nur die spezifischen Frames extra erstellt werden sollten.

Hier die Screens zum BeispieL: (in den 2 aus dem Editor sieht man, dass der einzige Unterschied in der subcat2 besteht)..
![metagroupsduplicateerror](https://user-images.githubusercontent.com/30180465/28368403-84ad03e0-6c94-11e7-9613-4fcab5e989fc.JPG)
![metagroupsduplicateerror2](https://user-images.githubusercontent.com/30180465/28368402-84ac5fd0-6c94-11e7-9449-ceee64e460d0.JPG)
![metagroupsduplicateerror3](https://user-images.githubusercontent.com/30180465/28368404-84b38454-6c94-11e7-9c03-a875a701d056.JPG)

**Comment by SebastianLasch** [comment]
@DanielPollithy 

Ich habe jetzt nochmal probiert und noch 2 Sachen bemerkt:
1. Es muss an der **Hand 1** liegen, weil ich im gleichen Fragment eine weitere Hand eröffnet habe und noch ein weiteren Frame (+Token) erstellt habe, welcher wieder 'Reference' heisst. Wenn ich dann übertrage, wird dieser Frame (der nur in einem Prop, nämlich 'subcat3' anders ist) an die bereits bestehenden MetaFrames angebunden. Also so, wie es sein sollte..Wenn ich in einer weiteren Hand probiere, dann geschieht dieser Fehler nicht, sondern die Frames werden den jeweiligen (vorhandenen) MetaFrames zugeordnet. 

2. Bei der Arbeit an diesem Beispiel, war plötzlich im Editor ein Frame "verschwunden", d.h. er wurde nicht mehr angezeigt (obwohl er in der Datenbank war). Ich hab ihn dann neu erstellt und dann war der "alte" weg und dafür der neue da. Danach wurde der Frame immer angezeigt.
___
Vielleicht ist das ganze zu kompliziert, um das hier zu erklären. Wir können uns auch gerne nochmal die nä tage treffen...

**Comment by DanielPollithy** [comment]
Hallo, @bastino089 !
Deine Beschreibung des Problems war sehr gut! Ich konnte den Fehler nachstellen.
![screenshot from 2017-08-10 11-32-55](https://user-images.githubusercontent.com/7472988/29164524-f69d71ba-7dbf-11e7-97a1-a7bd278bd394.png)

Ich habe die Datenbankoperationen, die beim Übertragen passieren, in eine feste Reihenfolge gebracht (davor konnten diese 'gleichzeitig' von statten laufen). Ich denke, das war ein Problem.

Mit dieser Änderung entsteht beim Übertragen kein zweiter MetaFrame (siehe folgendes Bild).
![screenshot from 2017-08-10 11-33-19](https://user-images.githubusercontent.com/7472988/29164595-42661dfe-7dc0-11e7-9cb0-5ece0c435360.png)

Für Punkt 2 wäre es wahrscheinlich das beste, wenn du ein neues Issue aufmachst. 
Wichtig ist, dass ich den Fehler nachstellen kann.
