### ISSUE TITLE
Frames and Meta Frames won't delete

### ISSUE THREAD

**Issue by SebastianLasch** [DanielPollithy/TransliterationApplication#98]
Servus Daniel,

wenn ich im Editor ein Fragment oder gesamtes Bild lösche, werden die Meta-/Frames nicht mitgelöscht.

Hier ein Bild aus neo4j:
![image](https://user-images.githubusercontent.com/30180465/29280283-edead018-811a-11e7-9d42-96ad2fb1d808.png)

**Comment by DanielPollithy** [comment]
Guter Fund! Die Groups werden jetzt gelöscht und nachdem man ein Fragment oder ein Bild gelöscht hat, wird nach MetaGroups ohne Verbindung gesucht. Diese werden dann auch gelöscht.
