### ISSUE TITLE
No auto-completion for Symbols, Frames, etc.

### ISSUE THREAD

**Issue by SebastianLasch** [DanielPollithy/TransliterationApplication#99]
Servus nochmal,
bei den Symbole, Frames, Blancos, Modifikationen gibt es nach wie vor keine Autovervollständigung (weder für die Properties, noch deren Inhalte). Wie wir das letzte mal besprochen haben, wäre das sehr sinnvoll!

Je nachdem wie groß der Aufwand dafür ist, wäre es toll, wenn du das hinzufügen könntest..

Das können wir aber auch nochmal besprechen..

Beste Grüße

**Comment by DanielPollithy** [comment]
Das Feature funktioniert jetzt bei allen einzelnen Typen und die Hintergrundattribute (wie zum Beispiel "x" oder "width") werden nicht mehr vorgeschlagen.
